### ISSUE TITLE
Legal team information out of date

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-website#5]
If you go to participate/legal team it directs you to the wiki: https://spdx.dev/participate/legal/

If you go to the legal team wiki page it has the uberconference URL: https://wiki.spdx.org/view/Legal_Team.  In my meeting invite I have zoom, so the either the Wiki needs to be updated or the website should point to information somewhere other than the wiki.

**Comment by kestewart** [comment]
@swinslow - can you confirm if this is still an issue?   I think it's fixed, but defer to you to close it, if so.

**Comment by swinslow** [comment]
@kestewart Apologies for slow action on this one. I've now updated the SPDX website legal team page with the 2023 calendar invite files.

Also added them to the [meetings repo](https://github.com/spdx/meetings#legal-team-meetings), other teams might consider doing so as well.
